// _gen/asdl/examples/demo_lib.asdl.cc is generated by asdl_main.py

#include "_gen/asdl/examples/demo_lib.asdl.h"
#include <assert.h>
#include "prebuilt/asdl/runtime.mycpp.h"  // generated code uses wrappers here

// Generated code uses these types
using hnode_asdl::hnode;
using hnode_asdl::Field;
using hnode_asdl::color_e;


namespace demo_lib_asdl {

BigStr* value_str(int tag, bool dot) {
  char buf[32];
  const char* v = nullptr;
  switch (tag) {
  case value_e::Str:
    v = "Str"; break;
  case value_e::Array:
    v = "Array"; break;
  default:
    assert(0);
  }
  if (dot) {
    snprintf(buf, 32, "value.%s", v);
    return StrFromC(buf);
  } else {
    return StrFromC(v);
  }
}

value__Str* value::Str = &gvalue__Str.obj;

GcGlobal<value__Str> gvalue__Str = 
  { ObjHeader::Global(value_e::Str) };

hnode_t* value__Str::PrettyTree(bool do_abbrev, Dict<int, bool>* seen) {
  seen = seen ? seen : Alloc<Dict<int, bool>>();
  int heap_id = ObjectId(this);
  if (dict_contains(seen, heap_id)) {
    return Alloc<hnode::AlreadySeen>(heap_id);
  }
  seen->set(heap_id, true);

  hnode::Record* out_node = runtime::NewRecord(value_str(this->tag()));
  return out_node;
}


hnode_t* value__Array::PrettyTree(bool do_abbrev, Dict<int, bool>* seen) {
  seen = seen ? seen : Alloc<Dict<int, bool>>();
  int heap_id = ObjectId(this);
  if (dict_contains(seen, heap_id)) {
    return Alloc<hnode::AlreadySeen>(heap_id);
  }
  seen->set(heap_id, true);

  hnode::Record* out_node = runtime::NewRecord(value_str(this->tag()));
  List<Field*>* L = out_node->fields;

  hnode_t* x0 = ToPretty(this->a);
  L->append(Alloc<Field>(StrFromC("a"), x0));

  return out_node;
}


hnode_t* value_t::PrettyTree(bool do_abbrev, Dict<int, bool>* seen) {
  switch (this->tag()) {
  case value_e::Str: {
    value__Str* obj = static_cast<value__Str*>(this);
    return obj->PrettyTree(do_abbrev, seen);
  }
  case value_e::Array: {
    value__Array* obj = static_cast<value__Array*>(this);
    return obj->PrettyTree(do_abbrev, seen);
  }
  default:
    assert(0);
  }
}

hnode_t* t2::PrettyTree(bool do_abbrev, Dict<int, bool>* seen) {
  seen = seen ? seen : Alloc<Dict<int, bool>>();
  int heap_id = ObjectId(this);
  if (dict_contains(seen, heap_id)) {
    return Alloc<hnode::AlreadySeen>(heap_id);
  }
  seen->set(heap_id, true);

  hnode::Record* out_node = runtime::NewRecord(StrFromC("t2"));
  List<Field*>* L = out_node->fields;

  hnode_t* x0 = ToPretty(this->a);
  L->append(Alloc<Field>(StrFromC("a"), x0));

  hnode_t* x1 = ToPretty(this->b);
  L->append(Alloc<Field>(StrFromC("b"), x1));

  return out_node;
}


hnode_t* t3::PrettyTree(bool do_abbrev, Dict<int, bool>* seen) {
  seen = seen ? seen : Alloc<Dict<int, bool>>();
  int heap_id = ObjectId(this);
  if (dict_contains(seen, heap_id)) {
    return Alloc<hnode::AlreadySeen>(heap_id);
  }
  seen->set(heap_id, true);

  hnode::Record* out_node = runtime::NewRecord(StrFromC("t3"));
  List<Field*>* L = out_node->fields;

  hnode_t* x0 = ToPretty(this->a);
  L->append(Alloc<Field>(StrFromC("a"), x0));

  hnode_t* x1 = ToPretty(this->b);
  L->append(Alloc<Field>(StrFromC("b"), x1));

  return out_node;
}


hnode_t* t4::PrettyTree(bool do_abbrev, Dict<int, bool>* seen) {
  seen = seen ? seen : Alloc<Dict<int, bool>>();
  int heap_id = ObjectId(this);
  if (dict_contains(seen, heap_id)) {
    return Alloc<hnode::AlreadySeen>(heap_id);
  }
  seen->set(heap_id, true);

  hnode::Record* out_node = runtime::NewRecord(StrFromC("t4"));
  List<Field*>* L = out_node->fields;

  hnode_t* x0 = ToPretty(this->a);
  L->append(Alloc<Field>(StrFromC("a"), x0));

  hnode_t* x1 = ToPretty(this->b);
  L->append(Alloc<Field>(StrFromC("b"), x1));

  return out_node;
}


hnode_t* LibToken::PrettyTree(bool do_abbrev, Dict<int, bool>* seen) {
  seen = seen ? seen : Alloc<Dict<int, bool>>();
  int heap_id = ObjectId(this);
  if (dict_contains(seen, heap_id)) {
    return Alloc<hnode::AlreadySeen>(heap_id);
  }
  seen->set(heap_id, true);

  hnode::Record* out_node = runtime::NewRecord(StrFromC("LibToken"));
  List<Field*>* L = out_node->fields;

  hnode_t* x0 = ToPretty(this->s);
  L->append(Alloc<Field>(StrFromC("s"), x0));

  hnode_t* x1 = ToPretty(this->i);
  L->append(Alloc<Field>(StrFromC("i"), x1));

  return out_node;
}


}  // namespace demo_lib_asdl
