// arg_types.cc is generated by frontend/flag_gen.py

#include "arg_types.h"
using runtime_asdl::flag_type_e;

namespace arg_types {

const char* arity0_3[] = {"P", "S", "V", "X", "l", "p", "s", "v", nullptr};

Action_c arity1_3[] = {
    {"f", ActionType_c::SetToString, "f", nullptr},
    {"m", ActionType_c::SetToString, "m", nullptr},
    {"q", ActionType_c::SetToString, "q", nullptr},
    {"r", ActionType_c::SetToString, "r", nullptr},
    {"u", ActionType_c::SetToString, "u", nullptr},
    {"x", ActionType_c::SetToString, "x", nullptr},
    {},
};

DefaultPair_c defaults_3[] = {
    {"P", flag_type_e::Bool, {.b = false}},
    {"S", flag_type_e::Bool, {.b = false}},
    {"V", flag_type_e::Bool, {.b = false}},
    {"X", flag_type_e::Bool, {.b = false}},
    {"f", flag_type_e::Str, {}},
    {"l", flag_type_e::Bool, {.b = false}},
    {"m", flag_type_e::Str, {}},
    {"p", flag_type_e::Bool, {.b = false}},
    {"q", flag_type_e::Str, {}},
    {"r", flag_type_e::Str, {}},
    {"s", flag_type_e::Bool, {.b = false}},
    {"u", flag_type_e::Str, {}},
    {"v", flag_type_e::Bool, {.b = false}},
    {"x", flag_type_e::Str, {}},
    {},
};

const char* arity0_7[] = {"L", "P", nullptr};

DefaultPair_c defaults_7[] = {
    {"L", flag_type_e::Bool, {.b = false}},
    {"P", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_8[] = {"V", "p", "v", nullptr};

DefaultPair_c defaults_8[] = {
    {"V", flag_type_e::Bool, {.b = false}},
    {"p", flag_type_e::Bool, {.b = false}},
    {"v", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_10[] = {"c", "l", "p", "v", nullptr};

DefaultPair_c defaults_10[] = {
    {"c", flag_type_e::Bool, {.b = false}},
    {"l", flag_type_e::Bool, {.b = false}},
    {"p", flag_type_e::Bool, {.b = false}},
    {"v", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_11[] = {"e", "n", nullptr};

DefaultPair_c defaults_11[] = {
    {"e", flag_type_e::Bool, {.b = false}},
    {"n", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c arity1_14[] = {
    {"a", ActionType_c::SetToString, "a", nullptr},
    {},
};

DefaultPair_c defaults_14[] = {
    {"a", flag_type_e::Str, {}},
    {},
};

const char* arity0_15[] = {"f", "n", "p", nullptr};

DefaultPair_c defaults_15[] = {
    {"f", flag_type_e::Bool, {.b = false}},
    {"n", flag_type_e::Bool, {.b = false}},
    {"p", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_18[] = {"l", "n", "r", nullptr};

Action_c arity1_18[] = {
    {"e", ActionType_c::SetToString, "e", nullptr},
    {},
};

DefaultPair_c defaults_18[] = {
    {"e", flag_type_e::Str, {}},
    {"l", flag_type_e::Bool, {.b = false}},
    {"n", flag_type_e::Bool, {.b = false}},
    {"r", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_21[] = {"r", nullptr};

DefaultPair_c defaults_21[] = {
    {"r", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_23[] = {"a", "c", "r", nullptr};

Action_c arity1_23[] = {
    {"d", ActionType_c::SetToInt, "d", nullptr},
    {},
};

DefaultPair_c defaults_23[] = {
    {"a", flag_type_e::Bool, {.b = false}},
    {"c", flag_type_e::Bool, {.b = false}},
    {"d", flag_type_e::Int, {.i = -1}},
    {"r", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c actions_long_24[] = {
    {"builtin", ActionType_c::SetToTrue, "builtin", nullptr},
    {"extern", ActionType_c::SetToTrue, "extern", nullptr},
    {"proc", ActionType_c::SetToTrue, "proc", nullptr},
    {"sh-func", ActionType_c::SetToTrue, "sh-func", nullptr},
    {"show", ActionType_c::SetToTrue, "show", nullptr},
    {},
};

DefaultPair_c defaults_24[] = {
    {"builtin", flag_type_e::Bool, {.b = false}},
    {"extern", flag_type_e::Bool, {.b = false}},
    {"proc", flag_type_e::Bool, {.b = false}},
    {"sh-func", flag_type_e::Bool, {.b = false}},
    {"show", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_25[] = {"l", "p", nullptr};

Action_c actions_long_25[] = {
    {"debug", ActionType_c::SetToTrue, "debug", nullptr},
    {},
};

DefaultPair_c defaults_25[] = {
    {"debug", flag_type_e::Bool, {.b = false}},
    {"l", flag_type_e::Bool, {.b = false}},
    {"p", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c actions_long_27[] = {
    {"indent", ActionType_c::SetToInt, "indent", nullptr},
    {},
};

DefaultPair_c defaults_27[] = {
    {"indent", flag_type_e::Int, {.i = 2}},
    {},
};

Action_c arity1_28[] = {
    {"L", ActionType_c::SetAttachedBool, "L", nullptr},
    {"l", ActionType_c::SetAttachedBool, "l", nullptr},
    {"n", ActionType_c::SetToString, "n", nullptr},
    {"s", ActionType_c::SetToString, "s", nullptr},
    {},
};

DefaultPair_c defaults_28[] = {
    {"L", flag_type_e::Bool, {.b = false}},
    {"l", flag_type_e::Bool, {.b = false}},
    {"n", flag_type_e::Str, {}},
    {"s", flag_type_e::Str, {}},
    {},
};

const char* arity0_29[] = {"t", nullptr};

DefaultPair_c defaults_29[] = {
    {"t", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_30[] = {"A", "F", "a", "f", "g", "i", "l", "p", "u", nullptr};

const char* plus_30[] = {"n", "r", "x", nullptr};

DefaultPair_c defaults_30[] = {
    {"A", flag_type_e::Bool, {.b = false}},
    {"F", flag_type_e::Bool, {.b = false}},
    {"a", flag_type_e::Bool, {.b = false}},
    {"f", flag_type_e::Bool, {.b = false}},
    {"g", flag_type_e::Bool, {.b = false}},
    {"i", flag_type_e::Bool, {.b = false}},
    {"l", flag_type_e::Bool, {.b = false}},
    {"n", flag_type_e::Str, {}},
    {"p", flag_type_e::Bool, {.b = false}},
    {"r", flag_type_e::Str, {}},
    {"u", flag_type_e::Bool, {.b = false}},
    {"x", flag_type_e::Str, {}},
    {},
};

Action_c arity1_33[] = {
    {"v", ActionType_c::SetToString, "v", nullptr},
    {},
};

DefaultPair_c defaults_33[] = {
    {"v", flag_type_e::Str, {}},
    {},
};

const char* arity0_36[] = {"L", "P", nullptr};

DefaultPair_c defaults_36[] = {
    {"L", flag_type_e::Bool, {.b = false}},
    {"P", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_37[] = {"Z", "r", "s", nullptr};

Action_c arity1_37[] = {
    {"N", ActionType_c::SetToInt, "N", nullptr},
    {"a", ActionType_c::SetToString, "a", nullptr},
    {"d", ActionType_c::SetToString, "d", nullptr},
    {"n", ActionType_c::SetToInt, "n", nullptr},
    {"p", ActionType_c::SetToString, "p", nullptr},
    {"t", ActionType_c::SetToFloat, "t", nullptr},
    {"u", ActionType_c::SetToInt, "u", nullptr},
    {},
};

Action_c actions_long_37[] = {
    {"all", ActionType_c::SetToTrue, "all", nullptr},
    {"num-bytes", ActionType_c::SetToInt, "num-bytes", nullptr},
    {"raw-line", ActionType_c::SetToTrue, "raw-line", nullptr},
    {"with-eol", ActionType_c::SetToTrue, "with-eol", nullptr},
    {},
};

DefaultPair_c defaults_37[] = {
    {"N", flag_type_e::Int, {.i = -1}},
    {"Z", flag_type_e::Bool, {.b = false}},
    {"a", flag_type_e::Str, {}},
    {"all", flag_type_e::Bool, {.b = false}},
    {"d", flag_type_e::Str, {}},
    {"n", flag_type_e::Int, {.i = -1}},
    {"num-bytes", flag_type_e::Int, {.i = -1}},
    {"p", flag_type_e::Str, {}},
    {"r", flag_type_e::Bool, {.b = false}},
    {"raw-line", flag_type_e::Bool, {.b = false}},
    {"s", flag_type_e::Bool, {.b = false}},
    {"t", flag_type_e::Float, {.f = -1.0}},
    {"u", flag_type_e::Int, {.i = -1}},
    {"with-eol", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_38[] = {"A", "a", "p", nullptr};

DefaultPair_c defaults_38[] = {
    {"A", flag_type_e::Bool, {.b = false}},
    {"a", flag_type_e::Bool, {.b = false}},
    {"p", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c arity1_40[] = {
    {"f", ActionType_c::SetAttachedBool, "f", nullptr},
    {},
};

DefaultPair_c defaults_40[] = {
    {"f", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c arity1_41[] = {
    {"h", ActionType_c::SetAttachedBool, "h", nullptr},
    {},
};

DefaultPair_c defaults_41[] = {
    {"h", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_42[] = {"o", "p", "q", "s", "u", nullptr};

Action_c actions_long_42[] = {
    {"set", ActionType_c::SetToTrue, "s", nullptr},
    {"unset", ActionType_c::SetToTrue, "u", nullptr},
    {},
};

DefaultPair_c defaults_42[] = {
    {"o", flag_type_e::Bool, {.b = false}},
    {"p", flag_type_e::Bool, {.b = false}},
    {"q", flag_type_e::Bool, {.b = false}},
    {"s", flag_type_e::Bool, {.b = false}},
    {"u", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c actions_long_45[] = {
    {"builtin", ActionType_c::SetToTrue, "builtin", nullptr},
    {},
};

DefaultPair_c defaults_45[] = {
    {"builtin", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_47[] = {"l", "p", nullptr};

Action_c actions_long_47[] = {
    {"add", ActionType_c::SetToTrue, "add", nullptr},
    {"ignore", ActionType_c::SetToTrue, "ignore", nullptr},
    {"remove", ActionType_c::SetToTrue, "remove", nullptr},
    {},
};

DefaultPair_c defaults_47[] = {
    {"add", flag_type_e::Bool, {.b = false}},
    {"ignore", flag_type_e::Bool, {.b = false}},
    {"l", flag_type_e::Bool, {.b = false}},
    {"p", flag_type_e::Bool, {.b = false}},
    {"remove", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c actions_long_48[] = {
    {"assign", ActionType_c::SetToString, "assign", nullptr},
    {},
};

DefaultPair_c defaults_48[] = {
    {"assign", flag_type_e::Str, {}},
    {},
};

const char* arity0_49[] = {"P", "a", "f", "p", "t", nullptr};

DefaultPair_c defaults_49[] = {
    {"P", flag_type_e::Bool, {.b = false}},
    {"a", flag_type_e::Bool, {.b = false}},
    {"f", flag_type_e::Bool, {.b = false}},
    {"p", flag_type_e::Bool, {.b = false}},
    {"t", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_50[] = {"H", "S", "a", "c", "d", "f", "n", "s", "t", "v", nullptr};

Action_c actions_long_50[] = {
    {"all", ActionType_c::SetToTrue, "all", nullptr},
    {},
};

DefaultPair_c defaults_50[] = {
    {"H", flag_type_e::Bool, {.b = false}},
    {"S", flag_type_e::Bool, {.b = false}},
    {"a", flag_type_e::Bool, {.b = false}},
    {"all", flag_type_e::Bool, {.b = false}},
    {"c", flag_type_e::Bool, {.b = false}},
    {"d", flag_type_e::Bool, {.b = false}},
    {"f", flag_type_e::Bool, {.b = false}},
    {"n", flag_type_e::Bool, {.b = false}},
    {"s", flag_type_e::Bool, {.b = false}},
    {"t", flag_type_e::Bool, {.b = false}},
    {"v", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_51[] = {"a", nullptr};

DefaultPair_c defaults_51[] = {
    {"a", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_52[] = {"f", "v", nullptr};

DefaultPair_c defaults_52[] = {
    {"f", flag_type_e::Bool, {.b = false}},
    {"v", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c actions_long_53[] = {
    {"extern", ActionType_c::SetToTrue, "extern", nullptr},
    {},
};

DefaultPair_c defaults_53[] = {
    {"extern", flag_type_e::Bool, {.b = false}},
    {},
};

const char* arity0_54[] = {"n", nullptr};

Action_c actions_long_54[] = {
    {"all", ActionType_c::SetToTrue, "all", nullptr},
    {"verbose", ActionType_c::SetToTrue, "verbose", nullptr},
    {},
};

DefaultPair_c defaults_54[] = {
    {"all", flag_type_e::Bool, {.b = false}},
    {"n", flag_type_e::Bool, {.b = false}},
    {"verbose", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c arity1_55[] = {
    {"n", ActionType_c::SetAttachedBool, "n", nullptr},
    {},
};

Action_c actions_long_55[] = {
    {"end", ActionType_c::SetToString, "end", nullptr},
    {"j8", ActionType_c::SetAttachedBool, "j8", nullptr},
    {"json", ActionType_c::SetAttachedBool, "json", nullptr},
    {"sep", ActionType_c::SetToString, "sep", nullptr},
    {},
};

DefaultPair_c defaults_55[] = {
    {"end", flag_type_e::Str, {.s = "\n"}},
    {"j8", flag_type_e::Bool, {.b = false}},
    {"json", flag_type_e::Bool, {.b = false}},
    {"n", flag_type_e::Bool, {.b = false}},
    {"sep", flag_type_e::Str, {.s = "\n"}},
    {},
};

FlagSpec_c kFlagSpecs[] = {
    { "alias", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "append", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "assert", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "bind", arity0_3, arity1_3, nullptr, nullptr, defaults_3 },
    { "boolstatus", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "builtin", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "cat", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "cd", arity0_7, nullptr, nullptr, nullptr, defaults_7 },
    { "command", arity0_8, nullptr, nullptr, nullptr, defaults_8 },
    { "ctx", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "dirs", arity0_10, nullptr, nullptr, nullptr, defaults_10 },
    { "echo", arity0_11, nullptr, nullptr, nullptr, defaults_11 },
    { "error", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "eval", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "exec_", nullptr, arity1_14, nullptr, nullptr, defaults_14 },
    { "export_", arity0_15, nullptr, nullptr, nullptr, defaults_15 },
    { "extern", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "failed", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "fc", arity0_18, arity1_18, nullptr, nullptr, defaults_18 },
    { "fork", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "forkwait", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "hash", arity0_21, nullptr, nullptr, nullptr, defaults_21 },
    { "help", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "history", arity0_23, arity1_23, nullptr, nullptr, defaults_23 },
    { "invoke", nullptr, nullptr, actions_long_24, nullptr, defaults_24 },
    { "jobs", arity0_25, nullptr, actions_long_25, nullptr, defaults_25 },
    { "json_read", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "json_write", nullptr, nullptr, actions_long_27, nullptr, defaults_27 },
    { "kill", nullptr, arity1_28, nullptr, nullptr, defaults_28 },
    { "mapfile", arity0_29, nullptr, nullptr, nullptr, defaults_29 },
    { "new_var", arity0_30, nullptr, nullptr, plus_30, defaults_30 },
    { "popd", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "pp", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "printf", nullptr, arity1_33, nullptr, nullptr, defaults_33 },
    { "push-registers", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "pushd", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "pwd", arity0_36, nullptr, nullptr, nullptr, defaults_36 },
    { "read", arity0_37, arity1_37, actions_long_37, nullptr, defaults_37 },
    { "readonly", arity0_38, nullptr, nullptr, nullptr, defaults_38 },
    { "redir", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "rm", nullptr, arity1_40, nullptr, nullptr, defaults_40 },
    { "runproc", nullptr, arity1_41, nullptr, nullptr, defaults_41 },
    { "shopt", arity0_42, nullptr, actions_long_42, nullptr, defaults_42 },
    { "shvar", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "sleep", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "source", nullptr, nullptr, actions_long_45, nullptr, defaults_45 },
    { "source-guard", nullptr, nullptr, nullptr, nullptr, nullptr },
    { "trap", arity0_47, nullptr, actions_long_47, nullptr, defaults_47 },
    { "try_", nullptr, nullptr, actions_long_48, nullptr, defaults_48 },
    { "type", arity0_49, nullptr, nullptr, nullptr, defaults_49 },
    { "ulimit", arity0_50, nullptr, actions_long_50, nullptr, defaults_50 },
    { "unalias", arity0_51, nullptr, nullptr, nullptr, defaults_51 },
    { "unset", arity0_52, nullptr, nullptr, nullptr, defaults_52 },
    { "use", nullptr, nullptr, actions_long_53, nullptr, defaults_53 },
    { "wait", arity0_54, nullptr, actions_long_54, nullptr, defaults_54 },
    { "write", nullptr, arity1_55, actions_long_55, nullptr, defaults_55 },
    {},
};

Action_c short_56[] = {
    {"n", ActionType_c::SetToString, "n", nullptr},
    {"s", ActionType_c::SetToTrue, "s", nullptr},
    {},
};

DefaultPair_c defaults_56[] = {
    {"n", flag_type_e::Str, {}},
    {"s", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c short_57[] = {
    {"c", ActionType_c::SetToString, "c", nullptr},
    {},
};

const char* params_0[] = {"jlines", "tsv8", nullptr};

Action_c long_57[] = {
    {"begin", ActionType_c::SetToInt, "begin", nullptr},
    {"end", ActionType_c::SetToInt, "end", nullptr},
    {"format", ActionType_c::SetToString, "format", params_0},
    {},
};

DefaultPair_c defaults_57[] = {
    {"begin", flag_type_e::Int, {.i = -1}},
    {"c", flag_type_e::Str, {}},
    {"end", flag_type_e::Int, {.i = -1}},
    {"format", flag_type_e::Str, {.s = "jlines"}},
    {},
};

const char* params_1[] = {"alias", "binding", "builtin", "command", "directory", "export", "file", "function", "helptopic", "job", "keyword", "setopt", "shopt", "signal", "stopped", "user", "variable", nullptr};

const char* params_2[] = {"bashdefault", "default", "dirnames", "filenames", "nospace", "plusdirs", nullptr};

Action_c short_58[] = {
    {"A", ActionType_c::SetNamedAction, nullptr, params_1},
    {"C", ActionType_c::SetToString, "C", nullptr},
    {"F", ActionType_c::SetToString, "F", nullptr},
    {"P", ActionType_c::SetToString, "P", nullptr},
    {"S", ActionType_c::SetToString, "S", nullptr},
    {"W", ActionType_c::SetToString, "W", nullptr},
    {"X", ActionType_c::SetToString, "X", nullptr},
    {"a", ActionType_c::SetAction, "alias", nullptr},
    {"b", ActionType_c::SetAction, "binding", nullptr},
    {"c", ActionType_c::SetAction, "command", nullptr},
    {"d", ActionType_c::SetAction, "directory", nullptr},
    {"e", ActionType_c::SetAction, "export", nullptr},
    {"f", ActionType_c::SetAction, "file", nullptr},
    {"j", ActionType_c::SetAction, "job", nullptr},
    {"k", ActionType_c::SetAction, "keyword", nullptr},
    {"o", ActionType_c::SetNamedOption, nullptr, params_2},
    {"u", ActionType_c::SetAction, "user", nullptr},
    {"v", ActionType_c::SetAction, "variable", nullptr},
    {},
};

const char* plus_2[] = {"o", nullptr};

DefaultPair_c defaults_58[] = {
    {"C", flag_type_e::Str, {}},
    {"F", flag_type_e::Str, {}},
    {"P", flag_type_e::Str, {}},
    {"S", flag_type_e::Str, {}},
    {"W", flag_type_e::Str, {}},
    {"X", flag_type_e::Str, {}},
    {},
};

const char* params_3[] = {"alias", "binding", "builtin", "command", "directory", "export", "file", "function", "helptopic", "job", "keyword", "setopt", "shopt", "signal", "stopped", "user", "variable", nullptr};

const char* params_4[] = {"bashdefault", "default", "dirnames", "filenames", "nospace", "plusdirs", nullptr};

Action_c short_59[] = {
    {"A", ActionType_c::SetNamedAction, nullptr, params_3},
    {"C", ActionType_c::SetToString, "C", nullptr},
    {"D", ActionType_c::SetToTrue, "D", nullptr},
    {"E", ActionType_c::SetToTrue, "E", nullptr},
    {"F", ActionType_c::SetToString, "F", nullptr},
    {"P", ActionType_c::SetToString, "P", nullptr},
    {"S", ActionType_c::SetToString, "S", nullptr},
    {"W", ActionType_c::SetToString, "W", nullptr},
    {"X", ActionType_c::SetToString, "X", nullptr},
    {"a", ActionType_c::SetAction, "alias", nullptr},
    {"b", ActionType_c::SetAction, "binding", nullptr},
    {"c", ActionType_c::SetAction, "command", nullptr},
    {"d", ActionType_c::SetAction, "directory", nullptr},
    {"e", ActionType_c::SetAction, "export", nullptr},
    {"f", ActionType_c::SetAction, "file", nullptr},
    {"j", ActionType_c::SetAction, "job", nullptr},
    {"k", ActionType_c::SetAction, "keyword", nullptr},
    {"o", ActionType_c::SetNamedOption, nullptr, params_4},
    {"u", ActionType_c::SetAction, "user", nullptr},
    {"v", ActionType_c::SetAction, "variable", nullptr},
    {},
};

const char* plus_3[] = {"o", nullptr};

DefaultPair_c defaults_59[] = {
    {"C", flag_type_e::Str, {}},
    {"D", flag_type_e::Bool, {.b = false}},
    {"E", flag_type_e::Bool, {.b = false}},
    {"F", flag_type_e::Str, {}},
    {"P", flag_type_e::Str, {}},
    {"S", flag_type_e::Str, {}},
    {"W", flag_type_e::Str, {}},
    {"X", flag_type_e::Str, {}},
    {},
};

const char* params_5[] = {"bashdefault", "default", "dirnames", "filenames", "nospace", "plusdirs", nullptr};

Action_c short_60[] = {
    {"o", ActionType_c::SetNamedOption, nullptr, params_5},
    {},
};

const char* plus_4[] = {"o", nullptr};

Action_c short_61[] = {
    {"C", ActionType_c::SetOption, "noclobber", nullptr},
    {"E", ActionType_c::SetOption, "errtrace", nullptr},
    {"O", ActionType_c::SetNamedOption_shopt, nullptr, nullptr},
    {"a", ActionType_c::SetOption, "allexport", nullptr},
    {"c", ActionType_c::SetToString_q, "c", nullptr},
    {"e", ActionType_c::SetOption, "errexit", nullptr},
    {"f", ActionType_c::SetOption, "noglob", nullptr},
    {"h", ActionType_c::SetOption, "hashall", nullptr},
    {"i", ActionType_c::SetToTrue, "i", nullptr},
    {"l", ActionType_c::SetToTrue, "l", nullptr},
    {"n", ActionType_c::SetOption, "noexec", nullptr},
    {"o", ActionType_c::SetNamedOption, nullptr, nullptr},
    {"u", ActionType_c::SetOption, "nounset", nullptr},
    {"v", ActionType_c::SetOption, "verbose", nullptr},
    {"x", ActionType_c::SetOption, "xtrace", nullptr},
    {},
};

const char* params_6[] = {"__dumpdoc", "__perf", "abbrev-text", "none", "text", nullptr};

const char* params_7[] = {"minimal", "nice", nullptr};

const char* params_8[] = {"cat-em", "deps", "find-lhs-array", "fmt", "lint", "lossless-cat", "syntax-tree", "test", "tokens", "ysh-ify", nullptr};

Action_c long_61[] = {
    {"ast-format", ActionType_c::SetToString, "ast-format", params_6},
    {"completion-demo", ActionType_c::SetToTrue, "completion-demo", nullptr},
    {"completion-display", ActionType_c::SetToString, "completion-display", params_7},
    {"debug-file", ActionType_c::SetToString, "debug-file", nullptr},
    {"do-lossless", ActionType_c::SetToTrue, "do-lossless", nullptr},
    {"eval", ActionType_c::AppendEvalFlag, "eval", nullptr},
    {"eval-pure", ActionType_c::AppendEvalFlag, "eval-pure", nullptr},
    {"headless", ActionType_c::SetToTrue, "headless", nullptr},
    {"help", ActionType_c::SetToTrue, "help", nullptr},
    {"location-start-line", ActionType_c::SetToInt, "location-start-line", nullptr},
    {"location-str", ActionType_c::SetToString, "location-str", nullptr},
    {"login", ActionType_c::SetToTrue, "login", nullptr},
    {"norc", ActionType_c::SetToTrue, "norc", nullptr},
    {"print-status", ActionType_c::SetToTrue, "print-status", nullptr},
    {"rcdir", ActionType_c::SetToString, "rcdir", nullptr},
    {"rcfile", ActionType_c::SetToString, "rcfile", nullptr},
    {"tool", ActionType_c::SetToString, "tool", params_8},
    {"version", ActionType_c::SetToTrue, "version", nullptr},
    {"xtrace-to-debug-file", ActionType_c::SetToTrue, "xtrace-to-debug-file", nullptr},
    {},
};

const char* plus_5[] = {"C", "E", "O", "a", "e", "f", "h", "n", "o", "u", "v", "x", nullptr};

DefaultPair_c defaults_61[] = {
    {"ast_format", flag_type_e::Str, {.s = "abbrev-text"}},
    {"c", flag_type_e::Str, {}},
    {"completion_demo", flag_type_e::Bool, {.b = false}},
    {"completion_display", flag_type_e::Str, {.s = "minimal"}},
    {"debug_file", flag_type_e::Str, {}},
    {"do_lossless", flag_type_e::Bool, {.b = false}},
    {"headless", flag_type_e::Bool, {.b = false}},
    {"help", flag_type_e::Bool, {.b = false}},
    {"i", flag_type_e::Bool, {.b = false}},
    {"l", flag_type_e::Bool, {.b = false}},
    {"location_start_line", flag_type_e::Int, {.i = -1}},
    {"location_str", flag_type_e::Str, {}},
    {"login", flag_type_e::Bool, {.b = false}},
    {"norc", flag_type_e::Bool, {.b = false}},
    {"print_status", flag_type_e::Bool, {.b = false}},
    {"rcdir", flag_type_e::Str, {}},
    {"rcfile", flag_type_e::Str, {}},
    {"tool", flag_type_e::Str, {.s = ""}},
    {"version", flag_type_e::Bool, {.b = false}},
    {"xtrace_to_debug_file", flag_type_e::Bool, {.b = false}},
    {},
};

Action_c short_62[] = {
    {"C", ActionType_c::SetOption, "noclobber", nullptr},
    {"E", ActionType_c::SetOption, "errtrace", nullptr},
    {"O", ActionType_c::SetNamedOption_shopt, nullptr, nullptr},
    {"a", ActionType_c::SetOption, "allexport", nullptr},
    {"e", ActionType_c::SetOption, "errexit", nullptr},
    {"f", ActionType_c::SetOption, "noglob", nullptr},
    {"h", ActionType_c::SetOption, "hashall", nullptr},
    {"n", ActionType_c::SetOption, "noexec", nullptr},
    {"o", ActionType_c::SetNamedOption, nullptr, nullptr},
    {"u", ActionType_c::SetOption, "nounset", nullptr},
    {"v", ActionType_c::SetOption, "verbose", nullptr},
    {"x", ActionType_c::SetOption, "xtrace", nullptr},
    {},
};

const char* plus_6[] = {"C", "E", "O", "a", "e", "f", "h", "n", "o", "u", "v", "x", nullptr};

FlagSpecAndMore_c kFlagSpecsAndMore[] = {
    { "compadjust", short_56, nullptr, nullptr, defaults_56 },
    { "compexport", short_57, long_57, nullptr, defaults_57 },
    { "compgen", short_58, nullptr, plus_2, defaults_58 },
    { "complete", short_59, nullptr, plus_3, defaults_59 },
    { "compopt", short_60, nullptr, plus_4, nullptr },
    { "main", short_61, long_61, plus_5, defaults_61 },
    { "set", short_62, nullptr, plus_6, nullptr },
    {},
};
}  // namespace arg_types
