cpp_namespace = 'syntax_asdl'
tags_to_types = \
{'InitializerWord_t': {1: 'InitializerWord__ArrayWord', 77: 'AssocPair'},
 'arith_expr_t': {1: 'arith_expr__EmptyZero',
                  2: 'arith_expr__EmptyOne',
                  5: 'arith_expr__UnaryAssign',
                  6: 'arith_expr__BinaryAssign',
                  7: 'arith_expr__Unary',
                  8: 'arith_expr__Binary',
                  9: 'arith_expr__TernaryOp',
                  67: 'Token',
                  68: 'CompoundWord'},
 'b_command_t': {93: 'VarDecl', 94: 'Mutation'},
 'bool_expr_t': {1: 'bool_expr__WordTest',
                 2: 'bool_expr__Binary',
                 3: 'bool_expr__Unary',
                 4: 'bool_expr__LogicalNot',
                 5: 'bool_expr__LogicalAnd',
                 6: 'bool_expr__LogicalOr'},
 'bracket_op_t': {1: 'bracket_op__WholeArray', 2: 'bracket_op__ArrayIndex'},
 'case_arg_t': {1: 'case_arg__Word', 2: 'case_arg__YshExpr'},
 'char_class_term_t': {104: 'PosixClass',
                       105: 'PerlClass',
                       106: 'CharCode',
                       107: 'CharRange'},
 'class_literal_term_t': {6: 'class_literal_term__Splice',
                          71: 'SingleQuoted',
                          104: 'PosixClass',
                          105: 'PerlClass',
                          106: 'CharCode',
                          107: 'CharRange'},
 'cmd_frag_t': {2: 'cmd_frag__Expr', 97: 'LiteralBlock'},
 'command_t': {1: 'command__NoOp',
               2: 'command__Redirect',
               3: 'command__Simple',
               4: 'command__ExpandedAlias',
               5: 'command__Sentence',
               6: 'command__ShAssignment',
               7: 'command__ControlFlow',
               8: 'command__Pipeline',
               9: 'command__AndOr',
               10: 'command__DoGroup',
               12: 'command__Subshell',
               13: 'command__DParen',
               14: 'command__DBracket',
               15: 'command__ForEach',
               16: 'command__ForExpr',
               17: 'command__WhileUntil',
               18: 'command__If',
               19: 'command__Case',
               21: 'command__TimeBlock',
               22: 'command__CommandList',
               24: 'command__BareDecl',
               29: 'command__Retval',
               86: 'BraceGroup',
               90: 'Proc',
               91: 'Func',
               93: 'VarDecl',
               94: 'Mutation',
               95: 'ExprCommand',
               96: 'ShFunction'},
 'condition_t': {2: 'condition__YshExpr', 81: 'List_of_command'},
 'debug_frame_t': {1: 'debug_frame__MainFile',
                   2: 'debug_frame__Dummy',
                   3: 'debug_frame__Source',
                   4: 'debug_frame__ProcLike',
                   7: 'debug_frame__BeforeErrTrap',
                   67: 'Token',
                   68: 'CompoundWord'},
 'expr_t': {1: 'expr__Var',
            2: 'expr__Const',
            3: 'expr__Place',
            12: 'expr__Literal',
            13: 'expr__Lambda',
            14: 'expr__Unary',
            15: 'expr__Binary',
            16: 'expr__Compare',
            17: 'expr__FuncCall',
            18: 'expr__IfExp',
            19: 'expr__Tuple',
            20: 'expr__List',
            21: 'expr__Dict',
            22: 'expr__Implicit',
            23: 'expr__ListComp',
            24: 'expr__DictComp',
            25: 'expr__GeneratorExp',
            26: 'expr__Range',
            27: 'expr__Slice',
            30: 'expr__Spread',
            69: 'BracedVarSub',
            70: 'DoubleQuoted',
            71: 'SingleQuoted',
            72: 'SimpleVarSub',
            73: 'CommandSub',
            74: 'ExprSub',
            75: 'YshArrayLiteral',
            84: 'Eggex',
            102: 'Subscript',
            103: 'Attribute'},
 'for_iter_t': {1: 'for_iter__Args',
                2: 'for_iter__Words',
                3: 'for_iter__YshExpr'},
 'glob_part_t': {1: 'glob_part__Literal',
                 2: 'glob_part__Operator',
                 3: 'glob_part__CharClass'},
 'loc_t': {1: 'loc__Missing',
           4: 'loc__WordPart',
           5: 'loc__Word',
           6: 'loc__Arith',
           7: 'loc__Command',
           67: 'Token',
           68: 'CompoundWord'},
 'parse_result_t': {1: 'parse_result__EmptyLine',
                    2: 'parse_result__Eof',
                    3: 'parse_result__Node'},
 'pat_t': {1: 'pat__Else', 2: 'pat__Words', 3: 'pat__YshExprs', 84: 'Eggex'},
 'place_op_t': {1: 'place_op__Subscript', 2: 'place_op__Attribute'},
 'printf_part_t': {2: 'printf_part__Percent', 67: 'Token'},
 'proc_sig_t': {1: 'proc_sig__Open', 2: 'proc_sig__Closed'},
 're_repeat_t': {2: 're_repeat__Range', 67: 'Token'},
 're_t': {1: 're__Primitive',
          4: 're__CharClassLiteral',
          5: 're__CharClass',
          6: 're__Splice',
          8: 're__Repeat',
          9: 're__Seq',
          10: 're__Alt',
          11: 're__Group',
          12: 're__Capture',
          13: 're__Backtracking',
          14: 're__LiteralChars',
          71: 'SingleQuoted',
          104: 'PosixClass',
          105: 'PerlClass'},
 'redir_loc_t': {1: 'redir_loc__Fd', 2: 'redir_loc__VarName'},
 'redir_param_t': {2: 'redir_param__HereWord',
                   3: 'redir_param__HereDoc',
                   68: 'CompoundWord'},
 'rhs_word_t': {1: 'rhs_word__Empty', 68: 'CompoundWord'},
 'sh_lhs_t': {1: 'sh_lhs__Name',
              2: 'sh_lhs__IndexedName',
              3: 'sh_lhs__UnparsedIndex'},
 'source_t': {1: 'source__Interactive',
              2: 'source__Headless',
              3: 'source__Unused',
              4: 'source__CFlag',
              5: 'source__Stdin',
              6: 'source__MainFile',
              7: 'source__OtherFile',
              8: 'source__Dynamic',
              9: 'source__VarRef',
              10: 'source__Variable',
              11: 'source__Alias',
              12: 'source__Reparsed',
              13: 'source__Synthetic'},
 'suffix_op_t': {2: 'suffix_op__Unary',
                 3: 'suffix_op__Static',
                 4: 'suffix_op__PatSub',
                 5: 'suffix_op__Slice',
                 67: 'Token'},
 'word_part_t': {2: 'word_part__InitializerLiteral',
                 4: 'word_part__EscapedLiteral',
                 9: 'word_part__ZshVarSub',
                 11: 'word_part__TildeSub',
                 12: 'word_part__ArithSub',
                 13: 'word_part__BracedTuple',
                 14: 'word_part__BracedRange',
                 15: 'word_part__BracedRangeDigit',
                 16: 'word_part__ExtGlob',
                 17: 'word_part__BashRegexGroup',
                 18: 'word_part__Splice',
                 67: 'Token',
                 69: 'BracedVarSub',
                 70: 'DoubleQuoted',
                 71: 'SingleQuoted',
                 72: 'SimpleVarSub',
                 73: 'CommandSub',
                 74: 'ExprSub',
                 75: 'YshArrayLiteral'},
 'word_t': {3: 'word__BracedTree',
            4: 'word__String',
            5: 'word__Redir',
            67: 'Token',
            68: 'CompoundWord'},
 'y_lhs_t': {67: 'Token', 102: 'Subscript', 103: 'Attribute'}}
