cpp_namespace = 'value_asdl'
tags_to_types = \
{'eggex_ops_t': {1: 'eggex_ops__No', 2: 'eggex_ops__Yes'},
 'regex_match_t': {1: 'regex_match__No', 68: 'RegexMatch'},
 'sh_lvalue_t': {2: 'sh_lvalue__Indexed',
                 3: 'sh_lvalue__Keyed',
                 67: 'LeftName'},
 'value_t': {1: 'value__Interrupted',
             2: 'value__Stdin',
             3: 'value__Slice',
             4: 'value__Undef',
             5: 'value__Str',
             6: 'value__InitializerList',
             7: 'value__InternalStringArray',
             8: 'value__BashArray',
             9: 'value__BashAssoc',
             10: 'value__Null',
             11: 'value__Bool',
             12: 'value__Int',
             13: 'value__Float',
             14: 'value__List',
             15: 'value__Dict',
             17: 'value__Range',
             18: 'value__Eggex',
             20: 'value__Place',
             21: 'value__Frame',
             22: 'value__DebugFrame',
             23: 'value__BoundFunc',
             24: 'value__BuiltinFunc',
             25: 'value__Func',
             26: 'value__BuiltinProc',
             27: 'value__Proc',
             28: 'value__Expr',
             29: 'value__CommandFrag',
             30: 'value__Command',
             68: 'RegexMatch',
             69: 'Obj'},
 'y_lvalue_t': {2: 'y_lvalue__Container', 67: 'LeftName'}}
